console.log('classPerson.js is connected');


const persons = [
  {
    name: 'Jay-Z',
    isbald: false,
    wasVegan: true,
    platinum: 'yes',
    isYoungerthan30: false,
    glasses: true,
    gender: 'male',
    hadbeefwithDrake: true,
    cream: false,
    realityShow: false,
    path: 'images/jay.jpg',
    id: "",
  },
  {
    name: 'Method Man',
    isbald: false,
    wasVegan: true,
    platinum: 'yes',
    isYoungerthan30: false,
    glasses: true,
    gender: 'male',
    hadbeefwithDrake: false,
    cream: false,
    realityShow: true,
    path: 'images/method.jpg',
    id: "",
  },
  {
    name: 'Nicki Minaj',
    isbald: false,
    wasVegan: true,
    platinum: 'yes',
    isYoungerthan30: true,
    glasses: true,
    gender: 'female',
    hadbeefwithDrake: true,
    cream: false,
    realityShow: true,
    barbie: true,
    path: 'images/nicki.jpg',
    id: "",
  },
  {
    name: 'DMX',
    isbald: false,
    wasVegan: true,
    platinum: 'yes',
    isYoungerthan30: false,
    glasses: true,
    gender: 'male',
    hadbeefwithDrake: true,
    cream: false,
    realityShow: false,
    path: 'images/dmx.jpg',
    id: "",
  },
  {
    name: 'Andre 3000',
    isbald: false,
    wasVegan: true,
    platinum: 'yes',
    isYoungerthan30: false,
    glasses: true,
    gender: 'male',
    hadbeefwithDrake: true,
    cream: false,
    realityShow: false,
    path: 'images/andre.png',
    id: "",
  },
  {
    name: 'Missy Elliott',
    isbald: false,
    wasVegan: true,
    platinum: 'yes',
    isYoungerthan30: false,
    glasses: true,
    gender: 'female',
    hadbeefwithDrake: true,
    cream: false,
    realityShow: false,
    path: 'images/missy.jpg',
    id: "",
  },
  {
    name: 'Wyclef Jean',
    isbald: false,
    wasVegan: true,
    platinum: 'yes',
    isYoungerthan30: false,
    glasses: true,
    gender: 'male',
    hadbeefwithDrake: true,
    cream: false,
    realityShow: false,
    path: 'images/wyclef.jpg',
    id: "",
  },
  {
   name: 'Vanilla Ice',
    isbald: true,
    wasVegan: false,
    platinum: 'yes',
    isYoungerthan30: false,
    glasses: true,
    gender: 'male',
    hadbeefwithDrake: true,
    cream: false,
    realityShow: true,
    path: 'images/vanilla.jpg',
    id: "",
  },
  {
    name: 'Iggy Azalea',
    isbald: false,
    wasVegan: true,
    platinum: 'yes',
    isYoungerthan30: true,
    glasses: true,
    gender: 'female',
    hadbeefwithDrake: true,
    cream: false,
    realityShow: false,
    path: 'images/iggy.jpg',
    id: "",
  },
  {
    name: 'Diddy',
    isbald: false,
    wasVegan: true,
    platinum: 'yes',
    isYoungerthan30: false,
    glasses: true,
    gender: 'male',
    hadbeefwithDrake: true,
    cream: false,
    realityShow: true,
    netWorth: true,
    path: 'images/diddy.jpg',
    id: "",
  },
  {
    name: 'Gucci Mane',
    isbald: false,
    wasVegan: true,
    platinum: 'yes',
    isYoungerthan30: false,
    glasses: true,
    gender: 'male',
    hadbeefwithDrake: true,
    cream: false,
    realityShow: false,
    path: 'images/gucci.jpg',
    id: "",
  },
  {
    name: 'Eminem',
    isbald: false,
    wasVegan: true,
    platinum: 'yes',
    isYoungerthan30: false,
    glasses: true,
    gender: 'male',
    hadbeefwithDrake: true,
    cream: false,
    realityShow: false,
    path: 'images/eminem.jpg',
    id: "",
  },
  {
    name: 'Lil Kim',
    isbald: false,
    wasVegan: true,
    platinum: 'yes',
    isYoungerthan30: false,
    glasses: true,
    gender: 'female',
    hadbeefwithDrake: true,
    cream: false,
    realityShow: false,
    path: 'images/lilkim.jpg',
    id: "",
  },
  {
    name: '50 Cent',
    isbald: false,
    wasVegan: true,
    platinum: 'yes',
    isYoungerthan30: false,
    glasses: true,
    gender: 'male',
    hadbeefwithDrake: true,
    cream: false,
    realityShow: true,
    path: 'images/fifty.jpg',
    currency: true,
    id: "",
  },
  {
    name: 'Ice T',
    isbald: false,
    wasVegan: true,
    platinum: 'yes',
    isYoungerthan30: false,
    glasses: true,
    gender: 'male',
    hadbeefwithDrake: true,
    cream: false,
    realityShow: true,
    path: 'images/iceT.png',
    id: "",
  },
  {
    name: 'Snoop',
    isbald: false,
    wasVegan: true,
    platinum: 'yes',
    isYoungerthan30: false,
    glasses: true,
    gender: 'male',
    hadbeefwithDrake: true,
    cream: false,
    realityShow: true,
    path: 'images/snoop.jpg',
    id: "",
  },
  {
    name: 'A$AP Rocky',
    isbald: false,
    wasVegan: true,
    platinum: 'yes',
    isYoungerthan30: false,
    glasses: true,
    gender: 'male',
    hadbeefwithDrake: true,
    cream: false,
    realityShow: false,
    path: 'images/asap.jpg',
    currency: true,
    id: "",
  },
  {
    name: 'ODB',
    isbald: false,
    wasVegan: true,
    platinum: 'yes',
    isYoungerthan30: false,
    glasses: true,
    gender: 'male',
    hadbeefwithDrake: false,
    cream: true,
    realityShow: false,
    deceased: true,
    path: 'images/odb.jpg',
    id: "",
  },
  {
    name: 'Kendrick Lamar',
    isbald: false,
    wasVegan: false,
    platinum: 'yes',
    isYoungerthan30: false,
    glasses: true,
    gender: 'male',
    hadbeefwithDrake: false,
    cream: false,
    realityShow: false,
    path: 'images/kendrick.jpg',
    id: "",
  },
  {
    name: 'IceCube',
    isbald: false,
    wasVegan: true,
    platinum: 'yes',
    isYoungerthan30: false,
    glasses: true,
    gender: 'male',
    hadbeefwithDrake: true,
    cream: false,
    realityShow: false,
    path: 'images/iceCube.jpg',
    id: "",
  },
  {
    name: 'Ludacris',
    isbald: false,
    wasVegan: true,
    platinum: 'yes',
    isYoungerthan30: false,
    glasses: true,
    gender: 'male',
    hadbeefwithDrake: true,
    cream: false,
    realityShow: false,
    path: 'images/ludacris.jpg',
    id: "",
  },
  {
    name: 'Lauryn Hill',
    isbald: false,
    wasVegan: true,
    platinum: 'yes',
    isYoungerthan30: false,
    glasses: true,
    gender: 'male',
    hadbeefwithDrake: true,
    cream: false,
    realityShow: false,
    path: 'images/lauryn.jpg',
    id: "",
  },
  {
    name: 'Dr. Dre',
    isbald: false,
    wasVegan: true,
    platinum: 'yes',
    isYoungerthan30: false,
    glasses: true,
    gender: 'male',
    hadbeefwithDrake: true,
    cream: false,
    realityShow: false,
    path: 'images/dr.jpg',
    id: "",
  },
  {
    name: 'Pharrell',
    isbald: false,
    wasVegan: true,
    platinum: 'yes',
    isYoungerthan30: false,
    glasses: true,
    gender: 'male',
    hadbeefwithDrake: true,
    cream: false,
    realityShow: false,
    group: false,
    path: 'images/pharrell.png',
    id: "",
  }
];

class Person {
  constructor(personObj, id) {
    this.isEliminated = false;
    this.id = id;
    for (let attribute in personObj) {
      this[attribute] = personObj[attribute];
    }
  }
}




